### ISSUE TITLE
Dial maneuver enhancement to allow for optional moves based on abilities and upgrades

### ISSUE THREAD

**Issue by PsyonicReign** [JohnnyCheese/TTS_X-Wing2.0#195] opened 2020-08-13 15:50 UTC
Countess Ryad, Slave 1, Hera Sydulla (both ship pilots), Grappling Struts, Landing Struts, Ved Foslo, R2-A6, Repulsorlift Stabilizers, Kaydel Connix, Seasoned Navigator, Inertial Dampeners, IG-88D pilot

these affect other ships:  Admiral Ozzel, Captain Needa, Strategic Commander, Saesee Tiin

**Comment by eirikmun** [comment] 2020-08-13 20:53
Duplicate of #42

**Closed by eirikmun** 2020-08-13 20:53 UTC
